artifacts_root: artifacts

data_ingestion:
  download_dir: Datasets/{dataset}
  datasets:
    brain_mri:
      display_name: BRAIN_MRI
      kaggle_dataset: navoneel/brain-mri-images-for-brain-tumor-detection
    strawberry_leaf:
      display_name: STRAWBERRY_LEAF
      kaggle_dataset: ashimdj89/plant-village-strawberry
    mvtec_ad_bottle:
      display_name: MVTEC_AD_BOTTLE
      kaggle_dataset: ashimdj89/mvtec-bottle

model_trainer:
  root_dir: artifacts/{dataset}/model_trainer
  models_dir: artifacts/{dataset}/model_trainer/saved_models
  extra_models_dir: trainedModels/{dataset}

model_evaluation:
  root_dir: resultAnalysis/{dataset}
  comparison_dir: resultAnalysis/{dataset}/comparison

ablation_analysis:
  root_dir: ablationAnalysis/{dataset}
  comparison_dir: ablationAnalysis/{dataset}/comparison
